### ISSUE TITLE
描画の重ね順を指定できるように希望します。

### ISSUE THREAD

**Issue by gahaku-tech** [sfc-sdp/GameCanvas-Unity#13]
`DrawImage	(int id,float x,float y) `する際に重ね順を指定できるようにしていただきたいです。

**Comment by seibe** [comment]
@gahaku-tech 
`DrawImage()` は呼び出し順 = 描画順になっていますが、引数を増やして呼び出し順と異なる描画順にしたいということでしょうか？

**Comment by gahaku-tech** [comment]
@seibe
はい、そういうことです。

**Comment by gahaku-tech** [comment]
`is Touch`で呼び出したものを上に載せたいと思っております。

**Comment by seibe** [comment]
@gahaku-tech 了解です。次かその次の更新で入れます。

**Comment by seibe** [comment]
反映が遅れててすみません。
 #9 と同じタイミングで入れられるように作業中です。

取り急ぎご報告まで

**Comment by seibe** [comment]
@gahaku-tech お待たせしました、v1.2.0 にて対応したので確認してみてください。
