### ISSUE TITLE
macOSエディターでプレビュー実行できない

### ISSUE THREAD

**Issue by demmys** [sfc-sdp/GameCanvas-Unity#201]
<img width="1552" alt="スクリーンショット 2021-02-07 16 57 17" src="https://user-images.githubusercontent.com/2297122/107140475-8c379b80-6965-11eb-99d4-710c119eb4f8.png">

**Comment by demmys** [comment]
GcInputPointerEngine内のTouchscreen.currentがnull

**Comment by demmys** [comment]
起動の仕方の問題?

**Comment by seibe** [comment]
あー、mac がタッチ非対応なのでエラってる模様

**Comment by demmys** [comment]
なるほど、デバイスシミュレータとかなんか使うようにすればいいとかあるのか...?
それかタッチのクラス自体をラップしないといけない?

**Comment by seibe** [comment]
こちらで暫定対応します。30分以内

**Comment by seibe** [comment]
@demmys 
これでどうでしょう
https://github.com/sfc-sdp/GameCanvas-Unity/releases/tag/v6.0.0-pre.5

**Comment by demmys** [comment]
@seibe だめみたい。
なんか独自のアサーションがNull検知しちゃってる?

<img width="1552" alt="スクリーンショット 2021-02-07 17 47 17" src="https://user-images.githubusercontent.com/2297122/107141526-8d1ffb80-696c-11eb-8089-def85b6029ef.png">

**Comment by demmys** [comment]
ちなみに、2行目のエラーを見るに、GameCanvasのOnDisable()の中のm_ProxyもNullになってるみたい。

**Comment by demmys** [comment]
あ、ていうかこれに引っかかっちゃってるのか
https://github.com/sfc-sdp/GameCanvas-Unity/pull/202/files#diff-d37af7844029881b2a3e2ca26584884d8aa34baef03cae919bc3c7a346dbc7f8R341

**Comment by demmys** [comment]
macOS環境でもPLATFORM_IOSがtrueになってるっぽい
![スクリーンショット 2021-02-07 18 10 39](https://user-images.githubusercontent.com/2297122/107142064-cc9c1700-696f-11eb-831b-3f5ac35a1892.png)

<img width="1552" alt="スクリーンショット 2021-02-07 18 11 08" src="https://user-images.githubusercontent.com/2297122/107142075-db82c980-696f-11eb-9e66-e475be32f678.png">

**Comment by demmys** [comment]
`#if` 消して実行するとちゃんと実行できる

**Comment by seibe** [comment]
理解した。いま mac を充電中なので、起動したら手元でもチェックします

昔と PLATFORM_*** の仕様が微妙に変わってる悪寒

**Comment by seibe** [comment]
今度こそ修正した

**Comment by demmys** [comment]
なおった!
