### ISSUE TITLE
gc.FillCircle ();について

### ISSUE THREAD

**Issue by tigerman-SFC** [sfc-sdp/GameCanvas-Unity#31]
Android端末にて上記関数を使うと、画面全体がピンク色になる。
gamecanvasのシェーダーの設定がおかしいと思われる。

**Comment by seibe** [comment]
@tigerman-SFC 報告ありがとうございます。
詳しく調べるので、該当のAndroid端末の型番を教えてください。

**Comment by seibe** [comment]
v2.0.0 でシェーダを変更したので閉じます
