### ISSUE TITLE
画像周辺の機能の要望

### ISSUE THREAD

**Issue by cagpie** [sfc-sdp/GameCanvas-Unity#38]
カメラからのイメージと、イメージのクリップ機能に関しての要望です。

・カメラのイメージを一時的に保存するなどして、DrawImageなどから任意のタイミングで使えるようにしたい
・主にカメラのイメージに対して、指定ピクセルの色を取得できるようにしたい

・DrawClippedImage、現在の切り取り方法が、画像の上下左右の切り取る長さを指定する方式になっているものを、指定のx,y座標から指定のwidth,height分だけ切り取る方式にしてほしい。もしくはそのような別の関数がほしい

以上です。よろしくおねがいします。

**Comment by seibe** [comment]
@cagpie 3787da7 にて、DrawClippedImageUVWH を追加しました。

カメラ関連は、後日対応します。

**Comment by seibe** [comment]
@cagpie dc19792 にて、カメラ映像のピクセル色情報を取得するAPIを追加しました

特定の1点の色情報を取得するには `gc.GetPixelOfCameraImage(int, int)` を使います。  
2点以上の色情報を取得するために、この関数を同一フレームで何度も呼ぶことは避けてください。

2点以上の色情報を取得するには `gc.GetPixelsOfCameraImage()` を使います。  
戻り値の `Colors` 構造体から `GetAt(int, int)` 関数で任意の座標の色情報を取得できます。

以下のコードは、16ピクセル間隔で色情報を取得することで カメラ映像をモザイク風に描画するサンプルです。

```cs
var colors = gc.GetColorsOfCameraImage();
for (var x = 0; x < gc.cameraImageWidth; x += 16)
{
    for (var y = 0; y < gc.cameraImageHeight; y += 16)
    {
        var color = colors.GetAt(x, y);
        gc.SetColor(color);
        gc.FillRect(x, y, 16, 16);
    }
}
```

**Comment by seibe** [comment]
v1.3.4 にてリリースしました
