### ISSUE TITLE
最新GCのDrawImageが正しく機能していない？

### ISSUE THREAD

**Issue by ShozenD** [sfc-sdp/GameCanvas-Unity#79]
なぜか一番最初の青空の写真しか読み込んでくれません。
ほかの画像にimg0.pngという名前をつけても読み込んでくれません。
また、青空の写真を別の番号にして読み込もうとすると失敗します。
確認をお願いします。

**Comment by seibe** [comment]
@ShozenD 
お問い合わせありがとうございます。
DrawImage の仕様を確認いただき、再度試してみていただけますでしょうか。
解決済みのであれば、その旨も書き込んでいただけると助かります。

画像は Asstes/Res フォルダ以下に img0, img1, img2 と被りなく連番で配置する必要があります。
このとき img1 の imageId は 1 になります。
番号が被っていたり、抜けていたりする場合の挙動は未定義です。
画像として認識されるファイルの拡張子は jpg, png, bmp などです。
