### ISSUE TITLE
Random(int, int)の使い方

### ISSUE THREAD

**Issue by ShozenD** [sfc-sdp/GameCanvas-Unity#80]
Random(int min, int max)
で生成される数値を変数に代入したいが、
random_num = Random(int min, int max)とおくとerrorがでます
どうしたらいいでしょうか？

**Comment by seibe** [comment]
@ShozenD 
質問ありがとうございます。

任意の範囲の乱数を取得する関数は [gc.Random(int min, int max)](https://sfc-sdp.github.io/GameCanvas-Unity/api/GameCanvas.Proxy.html#GameCanvas_Proxy_Random_System_Int32_System_Int32_) で合っています。
エラー内容が添えられていないので推測になりますが、関数の記述に誤りがあるのではないかと思います。

たとえば0以上10以下の乱数を取得する場合、下記のように記述します。
```cs
var randomNum = gc.Random(0, 10);
```
