### ISSUE TITLE
Time Out Function?

### ISSUE THREAD

**Issue by ShozenD** [sfc-sdp/GameCanvas-Unity#82]
GameCanvasでJavascriptのsetTimeout(); の様な一定時間になったら一度実行して終了する関数はありますか？
なければ自分でどのように作成したらいいでしょうか？

**Comment by seibe** [comment]
@ShozenD 
GameCanvas には、関数等を登録して一定時間後に実行するAPIはありません。

「n秒後に特定の処理を行う」という処理は、時間経過を監視して処理を分岐するコードで実現できます。（JSのsetTimeout等も内部ではそのような実装になっているはずです）

GameCanvas の時間経過を取得するAPIには、たとえば以下のようなものがあります。
- [gc.TimeSinceStartup](https://sfc-sdp.github.io/GameCanvas-Unity/api/GameCanvas.Proxy.html#GameCanvas_Proxy_TimeSinceStartup)
- [gc.CurrentTime](https://sfc-sdp.github.io/GameCanvas-Unity/api/GameCanvas.Proxy.html#GameCanvas_Proxy_CurrentTime)
