### ISSUE TITLE
タップしたら落ちる?

### ISSUE THREAD

**Issue by Chiji1108** [sfc-sdp/GameCanvas-Unity#91]
# 概要
トラックパッドでのタップでエラーが発生する
解決方法を知りたい
（既出だったら非常に申し訳ないです）
# 再現手順
`gc.GetPointerFrameCount(0)`を記載しているコードを実行させている時、ゲーム画面にカーソルを持っていきトラックパッドでタップすると以下のエラーを吐いてゲームが落ちる
```
KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <f2e6809acb14476a81f399aeb800f8f2>:0)
GameCanvas.Input.Pointer.OnBeforeUpdate () (at Assets/Plugins/GameCanvas/Scripts/Input/Pointer.cs:132)
GameCanvas.BehaviourBase.Update () (at Assets/Plugins/GameCanvas/Scripts/BehaviourBase.cs:100)
```
# 実行環境
 
| 環境 | バージョン |
|:-----------|:------------|
| macOS | 10.13 / 10.14<br />全てで確認 |
| Unity | 2017.4.1f1 / 2018.2.10f1<br />全てで確認|
| GameCanvas | 2.1.0 / 3.0.0 / 3.0.1 <br />全てで確認|

**Comment by seibe** [comment]
@Chiji1108 
不具合報告ありがとうございます。
こちらで再現確認が取れ、エディタ上でのタッチイベントシミュレートの不具合だと判明しました。
66cd29f にて修正を行い、 [v3.0.2](https://github.com/sfc-sdp/GameCanvas-Unity/releases/tag/v3.0.2) にてリリースしました。ご確認ください。

**Comment by Chiji1108** [comment]
@seibe 早い対応、誠にありがとうございます！！
