### ISSUE TITLE
文字入力フォーム関連のAPIの追加

### ISSUE THREAD

**Issue by Chiji1108** [sfc-sdp/GameCanvas-Unity#93]
# 概要 
文字入力フォーム関連のAPI？メソッド？を追加してほしい。
ソフトウェアキーボードを開いたり、打たれた文字を取得するメソッドがほしい。
# 目的
ユーザー名の登録、チャットなど
# 提案
実装が難しいor時間がかかりそうな場合は代替案を教えてもらえると嬉しいです…！

**Comment by seibe** [comment]
@Chiji1108 
UNity 2017.x 系で一度検討していたんですが、当時は iOS, Android で共通の挙動・インターフェースを実現することが難しいので見送っていました。
2018.x で可能かどうか、改めて検証してお返事します。

**Comment by seibe** [comment]
@Chiji1108 
念のため確認ですが、 `gc.ShowScreenKeyboard()` や `gc.GetIsKeyPress()` は試されましたか？

**Comment by Chiji1108** [comment]
@seibe 
すみません！！！！！`gc.ShowScreenKeyboard()`の存在を知りませんでした！！！！！！！
一度これでやれるところまでやってみます、ありがとうございます！
