### ISSUE TITLE
位置情報やカメラアクセスの権限について

### ISSUE THREAD

**Issue by Chiji1108** [sfc-sdp/GameCanvas-Unity#94]
# 概要
位置情報やカメラアクセスに関わるメソッドを利用していない場合には、権限の許可を問うダイアログが出ないようにしてほしい
# 再現手順
GameCanvasを利用したUnityでapkをビルドし、Android実機デバイスでインストールし起動した時、
位置情報やカメラアクセスに関わるメソッドを利用していない場合でも、初回起動時に位置情報とカメラアクセスの権限の付与に関してのダイアログが出る
# 実行環境
| 環境 | バージョン |
|:-----------|:------------|
| macOS | 10.14 |
| Unity | 2018.2.10f1|
| GameCanvas | 3.0.2|
| Android | 7.1.2|

**Comment by Chiji1108** [comment]
@seibe 
了解です、よろしくお願いします

**Comment by seibe** [comment]
v5.0.0 で対応しました
