### ISSUE TITLE
アスペクト比バグ

### ISSUE THREAD

**Issue by Chiji1108** [sfc-sdp/GameCanvas-Unity#95]
# 概要
特定の条件で下図のスクリーンショットのようにアスペクト比がおかしくなる  

![img_9114](https://user-images.githubusercontent.com/29515540/48334753-0dc4f400-e69f-11e8-91ba-846e15e1aa73.PNG)

# 再現手順
下記のコード([第6回講義での課題1](http://web.sfc.keio.ac.jp/~wadari/sdp/k06.html))をUnityRemote5でのiPhoneXで実行するとiPhoneXの画面でアスペクト比がおかしくなる

```C#

using Sequence = System.Collections.IEnumerator;

/// <summary>
/// ゲームクラス。
/// 学生が編集すべきソースコードです。
/// </summary>
public sealed class Game : GameBase
{

    /// <summary>
    /// 初期化処理
    /// </summary>
    public override void InitGame()
    {
        gc.SetResolution(720,1280);
    }

    /// <summary>
    /// 動きなどの更新処理
    /// </summary>
    public override void UpdateGame()
    {
        
    }

    /// <summary>
    /// 描画の処理
    /// </summary>
    public override void DrawGame()
    {
        gc.ClearScreen();
        gc.SetColor(0, 0, 0);
        gc.SetFontSize(36);
        gc.DrawString("AcceX:"+gc.AccelerationLastX,0,0);
        gc.DrawString("AcceY:"+gc.AccelerationLastY,0,40);
        gc.DrawString("AcceZ:"+gc.AccelerationLastZ,0,80);
    }
}
```
# 実行環境
 
| 環境 | バージョン |
|:-----------|:------------|
| macOS | 10.14.1 |
| Unity | 2018.2.10f1|
| GameCanvas | 3.0.2|
| iPhone X | 11.3.1|
| Unity Remote 5 | 2.0|

**Comment by seibe** [comment]
GameCanvas ではなく Unity Remote 5 の不具合です。
Unity Remote 5 は iPhoneX に対応していません。

**Comment by Chiji1108** [comment]
@seibe 
すみません、そういうことだったのですか
了解です、ありがとうございます！
