### ISSUE TITLE
複数のサウンドを同時に流せるようにしたうえで、個別のサウンドの再生状態や音量をコントロールできるように

### ISSUE THREAD

**Issue by Chiji1108** [sfc-sdp/GameCanvas-Unity#99]
## 概要
`PlaySound()`で流れているサウンドの各自の音量を指定できる、またはサウンドの再生開始位置を指定(途中から流すのようなこと)できるようにしてほしい
## 目的
変数によってBGMの内容を変更したい
例えば某マ〇オゲームのBGMが
・メロディパート
・ハモリパート
・ドラムパート
に分かれているとして、普段はメロディパートとドラムパートの同時再生だけだが、キノコを取っている状態の時だけハモリパートも追加される
のようなことを出来るようにしたい

**Comment by seibe** [comment]
@Chiji1108 提案ありがとうございます。
おそらくやりたいことは [こういうこと](https://www.nintendo.co.jp/jobs/introduction/sound/policy.html) ですよね。

現状のGameCanvasは同時にひとつの音源しか扱えませんが、これは歴史的経緯とプラットフォームの制限によるものです。
Unityにおいて前者は無意味ですから、複数同時に流せるように変更しようと思います。問題は後者ですね。

スマートデバイスはサウンドドライバに問題を抱えている機種が大変多く、音ゲーのような繊細な音源コントロールは実現できません。またメモリーも少ないため、同時再生できる音源数や音質には強い制限がかかります。
（このようなデバイスやUnityのお作法を真面目に習得しようとすると月単位の時間が過ぎていきますが、興味があれば[入門資料](https://www.slideshare.net/UnityTechnologiesJapan002/unite-tokyo-2018audio)とか覗いてみてください）

一旦 BGMは3つ、SEは5つまで同時再生可能という仕様で実装してみます。

**Comment by seibe** [comment]
[GameCanvas v3.1.0](https://github.com/sfc-sdp/GameCanvas-Unity/releases/tag/v3.1.0) でリリースしました。もし不具合があれば指摘してください。

**Comment by Chiji1108** [comment]
@seibe こういうことです！！！！！！本当にありがとうございます！！！！！！！！！何から何まで本当に…！！！
